# configuration for conversion to docs.globus.org
title: 'Transfer after Approval'
short_description: | 
  Allow users to transfer data into a secure enclave after obtaining an approval
  from a group of administrators.

example_dir: 'admin_signoff'
index_source:
  copy: "README.adoc"
append_source_blocks: true

menu_weight: 200
