# build and release new docs as a release asset
name: 📦 Package Docs
on:
  release:
    types: [created]

permissions:
  contents: "write"

jobs:
  doc:
    name: Bundle and Release Docs
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0' # v7.0.0
      - uses: 'actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1' # v6.3.0
        with:
          python-version: "3.13"
      - name: Install pipx
        run: python -m pip install pipx
      - name: Build the Doc Bundle
        run: |
          pipx run ./support/build-doc-bundle.py -o doc_bundle.tar.gz
      # upload as a release asset
      - name: Upload Doc Bundle
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "${{ github.ref_name }}" doc_bundle.tar.gz
